AWSTemplateFormatVersion: '2010-09-09'
Description: Security Group liberando acesso HTTP (porta 80)

Resources:
  MeuSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroupId:
    Description: ID do Security Group criado
    Value: !Ref MeuSecurityGroup
